### ISSUE TITLE
 draft-bw-alto-cost-mode: Change Typedef to Identity

### ISSUE THREAD

**Issue by dhruvdhody** [ietf-wg-alto/draft-ietf-alto-oam-yang#1]
Hi Jensen,

In light of  draft-bw-alto-cost-mode, we should change the typedef to identity to allow more cost modes to be defined in the future. I will raise an issue in github to track this as well 

     typedef cost-mode {
       type enumeration {
         enum numerical {
           value 1;
           description
             "This mode indicates that it is safe to perform numerical
              operations";
         }
         enum ordinal {
           value 2;
           description
             "This mode indicates that the cost values in a cost map
              represent ranking";
         }
       }
       description
         "The cost mode attribute indicates how costs should be
          interpreted. Specifically, the cost mode attribute indicates
          whether returned costs should be interpreted as numerical
          values or ordinal rankings.";
       reference
         "Section 6.1.2 of RFC 7285.";
     }
Thanks! 
Dhruv

**Comment by fno2010** [comment]
@dhruvdhody Do you think `identity` is better, or move `typedef` to an `iana-alto-types.yang` module is better? Just like what this YANG module does: https://github.com/YangModels/yang/blob/main/standard/ietf/RFC/iana-routing-types%402018-10-29.yang

**Comment by dhruvdhody** [comment]
Hi, I think it might be worth asking what is the current best practice here on when to create IANA-maintained models? Should we ask that to yang doctors perhaps?

**Comment by fno2010** [comment]
Make sense for me to ask YANG doctors. I just posted this question to YANG doctors: https://mailarchive.ietf.org/arch/msg/yang-doctors/rVflF_sVEv3fR4reZ6y93ikD2yE/

**Comment by boucadair** [comment]
Identity is used in the module instead of enums.
