### ISSUE TITLE
Statistic related to logging and fault management

### ISSUE THREAD

**Issue by fno2010** [ietf-wg-alto/draft-ietf-alto-oam-yang#2]
We need to give a proposal for [Sec 6.1 of draft-ietf-alto-oam-yang-00](https://datatracker.ietf.org/doc/html/draft-ietf-alto-oam-yang-00#section-6.1) to meet R2 and R4 in [Sec 4.2](https://datatracker.ietf.org/doc/html/draft-ietf-alto-oam-yang-00#section-4.2).

**Comment by fno2010** [comment]
Just checked the statement in the LMAP YANG Model draft [RFC8194]:

>    o  Logging Information: Some of the Logging Information, in
      particular 'success/failure/warning messages in response to
      information updates from the Controller', will be handled by the
      protocol used to manipulate the LMAP-specific configuration.  The
      LMAP data model defined in this document assumes that runtime
      Logging Information will be communicated using protocols that do
      not require a formal data model, e.g., the syslog protocol defined
      in [RFC5424].

Maybe ALTO should follow some similar principles to define the data model for logging and fault management.

**Comment by boucadair** [comment]
Can we tag this one as closed as both R2/R4 are covered by the model?
