### ISSUE TITLE
Add more discussion about the use of this feature

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-alto/draft-ietf-alto-oam-yang#27]
https://github.com/ietf-wg-alto/draft-ietf-alto-oam-yang/blob/17687c25e8350292559a800d65a1f484a66aa20e/yang/ietf-alto.yang#L62

**Comment by billwuqin** [comment]
It looks like debug mode. I agree we need to pay special attention to this feature.

**Comment by fno2010** [comment]
I also thought this should be some debug mode. But after rechecking the [`ietf-restconf-server.yang` module][1], it seems that the `http-listen` feature in the restconf model is used when the TLS is not handled by the implementor of this data model but an external gateway.

```
      case http {
        if-feature "http-listen";
        container http {
          description
            "Configures RESTCONF server stack assuming that
             TLS-termination is handled externally.";
```

[1]: https://github.com/YangModels/yang/blob/c49306baedc26bb49d4a683cedd23145e46bc9f9/experimental/ietf-extracted-YANG-modules/ietf-restconf-server%402022-12-12.yang#L181-L186

**Comment by boucadair** [comment]
I see that the YANG has now: 

            "... that
             TLS-termination is handled externally.";

We just need to add a mention to the security section about this. Will propose a PR for it.
