### ISSUE TITLE
Data model for ALTO client-side O&M

### ISSUE THREAD

**Issue by fno2010** [ietf-wg-alto/draft-ietf-alto-oam-yang#3]
This item requires more discussion.

**Comment by fno2010** [comment]
We do have several use cases which require O&M for ALTO clients. But I think the main concern is whether they require YANG techniques.

**Comment by fno2010** [comment]
The current client-side data model only includes server discovery config:

```
 module: ietf-alto
            +--rw alto!
               +--rw alto-client* [client-id]
               |  +--rw client-id                  string
               |  +--rw server-discovery-client
               |     +---u alto-server-discovery-client-grouping
               ...
```

It should be enough for some simple deployment. But more detailed configurations (e.g., `http-client-params`, periodical queries of interested information resources) are also good to be considered. Even if they are considered to be out of scope for the base module, maybe they are valuable for extended modules.

So I prefer to keep this issue open to track further discussions.

**Comment by billwuqin** [comment]
Here is the snippetof alto client:
     +--rw alto-client* [client-id] {alto-client}?
     |  +--rw client-id                  string
     |  +--rw server-discovery-client
     |     +--rw (server-discovery-client-manner)?
     |        +--:(reverse-dns) {xdom-disc}?
     |           +--rw rdns-params
     |              +--rw dns-server*   inet:host

I think the naming of the node "server-discovery-client" is confusing, s/server-discovery-client/server-discovery.
Also I am wondering whether we should also support ALTO server discovery in P2P scenario (ALTO client is
embedded in the resource consumer) described in RFC7286.
I think we can add one case for server discovery described in RFC7286.

**Comment by boucadair** [comment]
Can we close this one when merging #65?
