### ISSUE TITLE
choice/case + when statements

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-alto/draft-ietf-alto-oam-yang#30]
https://github.com/ietf-wg-alto/draft-ietf-alto-oam-yang/blob/2000bbb10681deda59581aaefeda26597eace813/yang/ietf-alto.yang#L991

The "case" statements can be replaced by having the "when" statements inside each container "container alto-ird-params". If you want to maintain the choice/case, then consider remove the "when" statements.

**Comment by billwuqin** [comment]
It is rare to see when and case statement are used at the same time. I agree this should be fixed.
See example as follows:
"
          case update {
            when 'derived-from-or-self(resource-type,'
               + '"alto:update")';
            if-feature "incr-update";
            container alto-update-params {
              description
                "Incremental Updates specific configuration.";
              uses algorithm;
            }
          }
"

**Comment by fno2010** [comment]
I agree. But the `when` statements cannot be removed. We need to check the `resource-type`. We have removed choice/case statements are removed and moved each `when` statement to each container inside.

**Comment by boucadair** [comment]
Thanks, @fno2010. No need to remove them as you removed choice/case.
