### ISSUE TITLE
Add energy and CO2 related metrics

### ISSUE THREAD

**Issue by janlindblad** [ietf-wg-alto/draft-ietf-alto-oam-yang#35]
In the YANG module ietf-alto, there are about a dozen cost-metric based identities. None of them relate to the energy usage or co2-footprint. Many service providers consider these cost aspects important for the resource allocation in the delivered services today, and project that the importance should increase in the foreseeable future.

It appears easy to add these aspects into the existing architecture. Probably in form of additional identities, but possibly not limited to that.

**Comment by fno2010** [comment]
@janlindblad The YANG module `ietf-alto` only includes cost metrics that have been already defined in RFCs. The costs related to energy usage or co2-footprint are very interesting. If they are proven to be beneficial and proposed to be standards later, the YANG module will definitely add them.

Are you willing to post this discussion to the ALTO WG mailing list (alto@ietf.org)? I believe other ALTO experts from WG can give more feedback.

**Comment by fno2010** [comment]
There is a list of all the cost metrics registered to IANA: https://www.iana.org/assignments/alto-protocol/alto-protocol.xhtml#cost-metrics

**Comment by boucadair** [comment]
This will be considered as an augmentation in future extensions.
