### ISSUE TITLE
Clarify typedef of list keys

### ISSUE THREAD

**Issue by fno2010** [ietf-wg-alto/draft-ietf-alto-oam-yang#37]
- there are 3 list keys that use unconstrained 'string'
  as the data type

  - /alto/alto-client/client-id
  - /alto/alto-server/cost-type/cost-type-name
  - /alto/alto-server/role/role-name
  - /alto/alto-server/data-source/source-id

- the 'resource-id' is done correctly, using a well-constrained
  typedef to define the key leaf.

- A similar typedef for each of these 3 types is needed.
  The constraints do not have to be the same.
  Machine-readable stmts are preferred but description
  is just as normative as 'pattern'.

- the typedef should clarify the following issues:

  - semantics:

    - it should be clear if the name has any
      special meaning or derived from a field defined
      in a document.
    - Use 'reference' if possible to define the linkage.

  - whitespace:
    - leading or trailing whitespace allowed?
    - whitespace within the key string value allowed?

  - zero-length: if not allowed then a minimum length of 1
    should be specified.

  - max-length:
    - it may be desirable to pick a maximum string length
      - example with limit: range "1 .. 64";
      - without limit: range "1 .. max";
    - there are some engineering trade-offs to consider.
      Details are out of scope here.

  - allowed characters:
    - use of plain string means the server is expected to
      support the entire character set.  If this is not
      what is desired then limit the character set with a
      pattern or a description-stmt.

**Comment by fno2010** [comment]
New typedefs have been added. But need to mention that there is no standard that can be referenced for `role-name` and `source-id`.

https://github.com/ietf-wg-alto/draft-ietf-alto-oam-yang/blob/6f2c3226961268213f3a22793c83eefe6d732f8a/yang/ietf-alto.yang#L416-L496

**Comment by boucadair** [comment]
As I don't see any PR linked to this one, what is the current status of this one? Are all the typedefs refer to what is in the base spec with no additional constraint? Thanks.

**Comment by fno2010** [comment]
As I mentioned in the previous reply, there is no standard defining encoding of `role-name` and `source-id`. All the other typedefs have referred to what is in the base spec.
