### ISSUE TITLE
Configuration for server level management

### ISSUE THREAD

**Issue by fno2010** [ietf-wg-alto/draft-ietf-alto-oam-yang#4]
This is required by [R1 in Sec 4.2](https://datatracker.ietf.org/doc/html/draft-ietf-alto-oam-yang-00#section-4.2).

Some questions from WG need to be considered:

- Question from Quifang Ma:  Should HTTP-server related configuration be in our scope(e.g., cache-control, Retry-After)?
  - https://mailarchive.ietf.org/arch/msg/alto/ZLV1cQIaSjYLeQ3KPh3ykJ3YMq8/

**Comment by dhruvdhody** [comment]
ONe reference to check out would be https://datatracker.ietf.org/doc/draft-ietf-netconf-http-client-server/ 
I cant find there, perhaps part of some groupings?

**Comment by fno2010** [comment]
Nice reference. Also, it seems that https://datatracker.ietf.org/doc/html/draft-ietf-netconf-restconf-client-server-25#section-3.1.2.2 can be a good example of how to use those groupings.
