### ISSUE TITLE
Add guidance on the empty placeholders `source-params` and `algorithm`

### ISSUE THREAD

**Issue by fno2010** [ietf-wg-alto/draft-ietf-alto-oam-yang#42]
`/alto/alto-server/data-source/source-params`

- Not much guidance or description on this placeholder choice.
  I understand you do not want to reference the 'example'
  YANG modules that augment this choice.

- Please add a reference or description mentioning the
  section in this RFC that explains the source params
  augmentation model.

        choice source-params {
          description
            "Data source specific configuration.";
        }

- Same comment on grouping `algorithm` as `source-params`.
- Provide reference or other guidance how this mandatory
  empty choice is used.

         grouping algorithm {
          description
            "This grouping defines the base data model for information
             resource creation algorithm.";
          choice algorithm {
            mandatory true;
            description
              "Information resource creation algorithm to be augmented.";
          }
        }

**Comment by fno2010** [comment]
Added references for `source-params` and `algorithm`:

https://github.com/ietf-wg-alto/draft-ietf-alto-oam-yang/blob/6f2c3226961268213f3a22793c83eefe6d732f8a/yang/ietf-alto.yang#L1062-L1066

https://github.com/ietf-wg-alto/draft-ietf-alto-oam-yang/blob/6f2c3226961268213f3a22793c83eefe6d732f8a/yang/ietf-alto.yang#L593-L599

**Comment by boucadair** [comment]
Can we close this one?
