### ISSUE TITLE
Do we really need endpoint-cost-cap grouping?

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-alto/draft-ietf-alto-oam-yang#51]
https://github.com/ietf-wg-alto/draft-ietf-alto-oam-yang/blob/7b10751db38991a6e949f3ce5e854ad8de707c05/yang/ietf-alto.yang#L655

This grouping does only use another existing grouping!

**Comment by fno2010** [comment]
Yes, they are the same. I thought they could be augmented by extension modules separately. But it seems that groupings cannot be augmented. The augmentation should be added to containers.
