### ISSUE TITLE
Fix Formatting in Section 6.1

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-alto/draft-ietf-alto-oam-yang#69]
>    More specifically, 'num-total-_' and 'num-total-last-_' provide
>    server-level failure counters; 'num-res-_' and 'num-res-last-_'
>    provide information resource-level failure counters.

Should be 

>    More specifically, 'num-total-*' and 'num-total-last-*' provide
>    server-level failure counters; 'num-res-*' and 'num-res-last-*'
>    provide information resource-level failure counters.

**Comment by fno2010** [comment]
I don't see any difference between the old and new paragraphs. But It looks like the `*` chars are not escaped.

The following change should fix this:

~~~
'num-total-*' -> 'num-total-\*'
~~~

I see the PR tries to use code blocks. It may generate redundant tags in XML.
