### ISSUE TITLE
Check that all JSON Examples comply with the YANG Modules

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-alto/draft-ietf-alto-oam-yang#8]
You may use https://github.com/CZ-NIC/yangson

**Comment by fno2010** [comment]
Thanks, Med. We do plan to use yangson in the OpenALTO implementation. For the draft, do you think we should also add some JSON examples? I see many other YANG-related drafts provide NETCONF XML examples instead of JSON.

**Comment by boucadair** [comment]
> For the draft, do you think we should also add some JSON examples?

I think so. JSON is much more friendly for readers. Thanks.
